CREATE SEQUENCE SEQ_BOARD;

DROP SEQUENCE SEQ_BOARD

CREATE TABLE TBL_BOARD(
	BNO NUMBER(10, 0),
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	WRITER VARCHAR2(50) NOT NULL,
	REGDATE DATE DEFAULT SYSDATE,
	UPDATEDATE DATE DEFAULT SYSDATE
	)
	
ALTER TABLE TBL_BOARD ADD CONSTRAINT PK_BOARD PRIMARY KEY (BNO);

INSERT INTO TBL_BOARD(BNO, TITLE, CONTENT, WRITER)
VALUES (SEQ_BOARD.NEXTVAL, '테스트 제목 01', '테스트 내용 01', 'USER00');
INSERT INTO TBL_BOARD(BNO, TITLE, CONTENT, WRITER)
VALUES (SEQ_BOARD.NEXTVAL, '테스트 제목 02', '테스트 내용 02', 'USER00');
INSERT INTO TBL_BOARD(BNO, TITLE, CONTENT, WRITER)
VALUES (SEQ_BOARD.NEXTVAL, '테스트 제목 03', '테스트 내용 03', 'USER00');
INSERT INTO TBL_BOARD(BNO, TITLE, CONTENT, WRITER)
VALUES (SEQ_BOARD.NEXTVAL, '테스트 제목 04', '테스트 내용 04', 'USER00');
INSERT INTO TBL_BOARD(BNO, TITLE, CONTENT, WRITER)
VALUES (SEQ_BOARD.NEXTVAL, '테스트 제목 05', '테스트 내용 05', 'USER00');
INSERT INTO TBL_BOARD(BNO, TITLE, CONTENT, WRITER)
VALUES (SEQ_BOARD.NEXTVAL, '테스트 제목 06', '테스트 내용 06', 'USER00');
INSERT INTO TBL_BOARD(BNO, TITLE, CONTENT, WRITER)
VALUES (SEQ_BOARD.NEXTVAL, '테스트 제목 07', '테스트 내용 07', 'USER00');
INSERT INTO TBL_BOARD(BNO, TITLE, CONTENT, WRITER)
VALUES (SEQ_BOARD.NEXTVAL, '테스트 제목 08', '테스트 내용 08', 'USER00');

SELECT * FROM TBL_BOARD;