CREATE USER book_ex IDENTIFIED BY book_ex 
DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP

GRANT CONNECT, DBA TO book_ex

DROP USER book_ex

SELECT DBMS_XDB.GETHTTPPORT() FROM DUAL; --오라클 포트 확인용
EXEC DBME_XDB.SETHTTPPORT(9999); --cmd용