CREATE SEQUENCE SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE

CREATE TABLE MEMBER(
	MNO NUMBER(10) PRIMARY KEY,
	NAME VARCHAR2(10) NOT NULL,
	BIRTH VARCHAR2(8) NOT NULL,
	EMAIL VARCHAR2(20) NOT NULL
	)
	
CREATE TABLE BOARD(
	BNO NUMBER(10) PRIMARY KEY,
	WRITER NUMBER(10) NOT NULL,
	TITLE VARCHAR2(20) NOT NULL,
	CONTENT VARCHAR2(150) NOT NULL,
	REGIDATE DATE DEFAULT SYSDATE,
	UPDADATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_MEM FOREIGN KEY (WRITER) REFERENCES MEMBER(MNO)
	)
	
INSERT INTO MEMBER VALUES (SEQ.NEXTVAL, 'NAME1', '20010101', 'ABC11@EMAIL.COM');
INSERT INTO MEMBER VALUES (SEQ.NEXTVAL, 'NAME2', '20010102', 'ABC22@EMAIL.COM');
INSERT INTO MEMBER VALUES (SEQ.NEXTVAL, 'NAME3', '20010103', 'ABC33@EMAIL.COM');
INSERT INTO MEMBER VALUES (SEQ.NEXTVAL, 'NAME4', '20010104', 'ABC44@EMAIL.COM');
INSERT INTO MEMBER VALUES (SEQ.NEXTVAL, 'NAME5', '20010105', 'ABC55@EMAIL.COM');

DELETE FROM MEMBER
SELECT * FROM MEMBER

INSERT INTO BOARD (BNO, WRITER, TITLE, CONTENT) VALUES (SEQ.NEXTVAL, 2, 'TITLE1', 'CONTENT1');
INSERT INTO BOARD (BNO, WRITER, TITLE, CONTENT) VALUES (SEQ.NEXTVAL, 3, 'TITLE2', 'CONTENT2');
INSERT INTO BOARD (BNO, WRITER, TITLE, CONTENT) VALUES (SEQ.NEXTVAL, 4, 'TITLE3', 'CONTENT3');
INSERT INTO BOARD (BNO, WRITER, TITLE, CONTENT) VALUES (SEQ.NEXTVAL, 5, 'TITLE4', 'CONTENT4');
INSERT INTO BOARD (BNO, WRITER, TITLE, CONTENT) VALUES (SEQ.NEXTVAL, 6, 'TITLE5', 'CONTENT5');

DELETE FORM BOARD;
SELECT * FROM BOARD;

