CREATE USER TESTDB IDENTIFIED BY TESTDB
DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP

GRANT CONNECT, RESOURCE TO TESTDB

SELECT DBMS_XDB.GETHTTPPORT() FROM DUAL --오라클 포트 확인용

EXEC DBMS_XDB.SETHTTPPORT(9999) --CMD용
